version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Test
          command: dotnet test
workflows:
  build-and-test:
    jobs:
      - build-and-test